name: "gp-m52"

num_chains: 1
num_warmup: 50
num_samples: 50
max_treedepth: 13
thinning: 1


numpyro_model: 
  _partial_: true
  _target_: bayes_rate_consistency.model.simulation_model_gp

load_decoder: False