name: "gp-m52"

num_chains: 4
num_warmup: 500
num_samples: 1500
max_treedepth: 13
thinning: 1


numpyro_model: 
  _partial_: true
  _target_: bayes_rate_consistency.model.simulation_model_gp

load_decoder: False