name: "vae-m52"

num_chains: 4
num_warmup: 500
num_samples: 1000
max_treedepth: 13
thinning: 1

input_dim : 1936
hidden_dim1: 1500
hidden_dim2: 1000
hidden_dim3: 500
latent_dim: 30

decoder_path: "weights/model_large_9000_mat52_0.1"

numpyro_model: 
  _partial_: true
  _target_: bayes_rate_consistency.model.simulation_model_vae


load_decoder: True